baseURL = "https://inbetweennames.net/"
title = "Shane Peelar's Blog"
theme = "manis"

buildDrafts = true

# Copyright notice. Note: You can use HTML tag here
copyright = "&copy; 2021 Shane Peelar"
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 10

# Your disqus shortname
disqusShortname = ""

# Edit this if you want to translate your blog
defaultContentLanguage = "en"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
	tag = "tags"

[markup.goldmark.renderer]
unsafe= true

[params]
  authorname = "Shane Peelar"

  # If false, use minified CSS (ui.min.css)
	debugCSS = true
	# Custom CSS
	customCSS = []

	# List of sections support disqus comments
	disqusSections = [ "blog" ]
	# Site meta description
	description = "International Journal of Cool and Interesting Things"
	# Site's Tagline (Subtitle or Keyword)
	tagline = "Computer Scientist (Ph.D.) / Dog Whisperer"
	professionalTagLine = "Computer Scientist (Ph.D.)"

  authorimg = "/img/maizyandme-180.jpg"
  professionalauthorimg = "/img/shane-180.jpg"
	# If true give attribution to this theme
	themeAttrib = true
	# URL to license file, can be outside of your domain
	#licenseURL = "/about/license"

	# Configure which section for Latest Posts
	postSection = "blog"
	# Configure which section for Latest Works
	workSection = "work"

	# 404 Configuration
	head404 = "Sorry, I can't find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	# Color of your website's accent
  foregroundColor = "#1c6e8c" #ff8181
	backgroundColor = "floralwhite"
  textColor = "#444"
  headingColor = "#222"
  taglineColor = "#898989"
  topSepColor = "#888888"
  dateColor = "#666"
  barNavColor = "#777"
  # Maximum number of item in Latest Posts or Works
	latestCount = 3
	# Path to site's favicon image
	faviconImg = ""
	# Date format in item list
	dateFmt = "2 Jan 2006"

	# Code Highlighting (HighlightJS)
	highlightJs = false
	highlightJsLanguages = [ "c++" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "lookatyouhacker@gmail.com"
	github = "https://github.com/InBetweenNames/"
  linkedin = "https://www.linkedin.com/in/shane-peelar-29a2005a/"

	#analytics
	matomo = "//matomo.inbetweennames.net/"

# Language Configuration
#[languages.in]
#	lang = "in"
#	languageName = "Bahasa Indonesia"
#	weight = 1
